Panoramix's Prediction.cpp
=> added  Panoramix's Prediction

StonesontheTable.cpp
@rohitsinghkcodes   please review
=> Added Stones on the Table

CODEFORCES Questions Solutions (CP)/drink.cpp
=> added drink file in codeforces

CODECHEF Questions Solutions (CP)/ADAKING.java
Added Codechef File and solution of ADAKNG question.
=> ADAKNG solution 

CODECHEF Questions Solutions (CP)/DIVSUBS.cpp
I have added code for DIVSUBS problem from codechef.
I'm planning to add some from Codechef, Codeforces and some standard DP problems.
If you have any suggestion for the format or anything, do let me know.
=> added DIVSUBS codechef

CODECHEF Questions Solutions (CP)/HMAPPY.cpp
Please review my PR for Hacktoberfest.
=> HMAPPY Codechef Solution Added

CODEFORCES Questions Solutions (CP)/B_Duff In Love.cpp, CODEFORCES Questions Solutions (CP)/B_Fox Dividing Cheese.cpp, CODEFORCES Questions Solutions (CP)/C_Hamburgers.cpp, CODEFORCES Questions Solutions (CP)/C_Kefa and Park.cpp, CODEFORCES Questions Solutions (CP)/C_Searching for graph.cpp
=> Added Some Codeforces Problems

LargestCommonSubsequence.java
This algorithm of the longest common subsequence (LCS) is for finding the longest subsequence common to all sequences in a set of sequences (often just two sequences). Here, I have used the memoization technique in Dynamic Programming.
=> LargestCommonSubsequence.java added

INTERVIEWBIT/Linked-Lists/Even_Reverse.py
Solution for Even Reverse Problem from InterviewBit Linked List.
Problem Statement: Given a linked list A, reverse the order of all nodes at even positions.
Problem Link:https://www.interviewbit.com/problems/even-reverse/
=> Solve Even Reverse Linked List

INTERVIEWBIT/Linked-Lists/Kth_Node_From_Middle.py, INTERVIEWBIT/Linked-Lists/Reverse Alternate K Nodes.py
Solution for the kth node from the middle problem from InterviewBit Linked Lists.
Problem Statement: Given a linked list A of length N and an integer B. You need to find the value of the Bth node from the middle towards the beginning of the Linked List A. If no such element exists, then return -1.
Problem Link: https://www.interviewbit.com/problems/kth-node-from-middle/
=> Solved Kth_Node_from_Middle from InterviewBit LinkedLists

INTERVIEWBIT/Arrays/Minimum_Lights_to_Activate.py
Solution for Minimum Lights to Activate the problem of InterviewBit Arrays.
Problem statement : There is a corridor in a Jail which is N units long. Given an array A of size N. The ith index of this array is 0 if the light at ith position is faulty otherwise it is 1.All the lights are of specific power B which if is placed at position X, it can light the corridor from [ X-B+1, X+B-1].Initially all lights are off.
Return the minimum number of lights to be turned ON to light the whole corridor or -1 if the whole corridor cannot be lighted.
Problem Link: https://www.interviewbit.com/problems/minimum-lights-to-activate/
=> Solved Minimum Lights to Activate

INTERVIEWBIT/Math/Permutation Sequence.cpp
Please Review And Merge
Thank you.
=> Create Permutation Sequence.cpp

Hackerrank-Solutions/Alphabet Rangoli.py, Hackerrank-Solutions/Alternating_Characters.py, Hackerrank-Solutions/Capitalize.py, Hackerrank-Solutions/Count_Triplets.py, Hackerrank-Solutions/Designer Door Mat.py, Hackerrank-Solutions/Find a string.py, Hackerrank-Solutions/Find the Runner-Up Score!.py, Hackerrank-Solutions/Finding the eprcentage.py, Hackerrank-Solutions/Introduction to Sets.py, Hackerrank-Solutions/Java 1D Array (Part 2).java, Hackerrank-Solutions/Java BigDecimal.java, Hackerrank-Solutions/Java Currency Formatter.java, Hackerrank-Solutions/Java Output Formatting.java, Hackerrank-Solutions/Java Regex 2 - Duplicate Words.java
Added few code solution snippets on Hackerrank Coding Questions for HacktoberFest 2020. Please review and accept the PR.
=> Added solutions related to Hackerrank Coding Questions

STACK_OPER
A menu driven program for case studies in stacks
=> STACK_OPER

CODEFORCES Questions Solutions (CP)/1030A_In_Search_of_an_Easy_Problem.cpp, CODEFORCES Questions Solutions (CP)/1154A_Restoring_Three_Numbers.cpp, CODEFORCES Questions Solutions (CP)/1312A_Two_Regular_Polygons.cpp, CODEFORCES Questions Solutions (CP)/1325A_EhAb_AnD_gCd.cpp, CODEFORCES Questions Solutions (CP)/1328A_Divisibility_Problem.cpp, CODEFORCES Questions Solutions (CP)/1335A_Candies_and_Two_Sisters.cpp, CODEFORCES Questions Solutions (CP)/1352A_Sum_of_Round_Numbers.cpp, CODEFORCES Questions Solutions (CP)/1370A_Maximum_GCD.cpp, CODEFORCES Questions Solutions (CP)/1388A_Captain_Flint_and_Crew_Recruitment.cpp, CODEFORCES Questions Solutions (CP)/1389A_LCM_Problem.cpp, CODEFORCES Questions Solutions (CP)/1417A_Copy_Paste.cpp, CODEFORCES Questions Solutions (CP)/266B_Queue_at_the_School.cpp, CODEFORCES Questions Solutions (CP)/268A_Games.cpp, CODEFORCES Questions Solutions (CP)/271A_Beautiful_Year.cpp, CODEFORCES Questions Solutions (CP)/281A_Word_Capitalization.cpp, CODEFORCES Questions Solutions (CP)/282A_Bit++.cpp, CODEFORCES Questions Solutions (CP)/306A_Candies.cpp, CODEFORCES Questions Solutions (CP)/339A_Helpful_Maths.cpp, CODEFORCES Questions Solutions (CP)/344A_Magnets.cpp, CODEFORCES Questions Solutions (CP)/443A_Anton_and_Letters.cpp, CODEFORCES Questions Solutions (CP)/467A_George_and_Accomodation.cpp, CODEFORCES Questions Solutions (CP)/749A_Bachgold_Problem.cpp, CODEFORCES Questions Solutions (CP)/750A_New_Year_and_Hurry.cpp, CODEFORCES Questions Solutions (CP)/755A_PolandBall_and_Hypothesis.cpp, CODEFORCES Questions Solutions (CP)/785A_Anton_and_Polyhedrons.cpp, CODEFORCES Questions Solutions (CP)/791A_Bear_and_Big_Brother.cpp, CODEFORCES Questions Solutions (CP)/822A_I'm_Bored_With_Life.cpp, CODEFORCES Questions Solutions (CP)/977A_Wrong_Subtraction.cpp, CODEFORCES Questions Solutions (CP)/996A_Hit_the_Lottery.cpp
solutions to 800 rated problems on code forces.
=> solutions to 800 rated problems on codeforces.

CODECHEF Questions Solutions (CP)/Average.cpp, CODECHEF Questions Solutions (CP)/Discrepancies_in_the_Voters_List.cpp, CODECHEF Questions Solutions (CP)/Dividing_Squences.cpp, CODECHEF Questions Solutions (CP)/End_of_Corruption.cpp, CODECHEF Questions Solutions (CP)/Find_the_Permutation.cpp, CODECHEF Questions Solutions (CP)/Lead_Game.cpp, CODECHEF Questions Solutions (CP)/List_of_Books.cpp, CODECHEF Questions Solutions (CP)/Longest_Palindrome.cpp, CODECHEF Questions Solutions (CP)/Next_Permutation.cpp, CODECHEF Questions Solutions (CP)/Permutation_Cycles.cpp, CODECHEF Questions Solutions (CP)/Reverse.cpp, CODECHEF Questions Solutions (CP)/Whats_the_Rank.cpp, CODECHEF Questions Solutions (CP)/Word_list.cpp, CODECHEF Questions Solutions (CP)/Zero_One_Tiles.cpp
solution to some of the problems which I have solved from the contest IARCAS OPC JUDGE Series
=> IARCS OPC JUDGE PROBLEMS

LeetCode-Solutions-CPP/BinarySearch_704.cpp, LeetCode-Solutions-CPP/BinaryToIntegerLinkedList_1290.cpp, LeetCode-Solutions-CPP/DeleteNodeLinkedLIst_237.cpp, LeetCode-Solutions-CPP/InstersectionLinkedList_160.cpp, LeetCode-Solutions-CPP/LinkedListCycle_141.cpp, LeetCode-Solutions-CPP/PalindromeLinkedList_234.cpp, LeetCode-Solutions-CPP/SearchInsertPosition_35.cpp, LeetCode-Solutions-CPP/ValidParentheses_20.cpp
Have created a separate folder for solutions of Leetcode in cpp and have added solutions to 8 of the problems. The file name mentions the problems name followed by the problem no.
(All these solutions are accepted on LeetCode)
=> Added LeetCode Solutions in CPP

CODEFORCES Questions Solutions (CP)/20C_Dijkstra.cpp
This solution has been accepted on CF.
=> Added CF 20C

SPOJ_LIST/LCM SUM.cpp
=> Create LCM SUM.cpp

CODEFORCES Questions Solutions (CP)/Subarray XOR.cpp
=> Create Subarray XOR.cpp
